import type { Metadata } from "next";
import { Poppins, Space_Mono } from "next/font/google";

import StoreProvider from "@/components/providers/store-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "./globals.css";

import { cn } from "@/lib/utils";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  variable: "--font-space-mono",
});

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(spaceMono.className, poppins.className, "antialiased")}
      >
        <NuqsAdapter>
          <StoreProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </StoreProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
